import type { PublishedReferenceLimit, DirectDashboardLink } from '../contracts';

export const PUBLISHED_REFERENCE_LIMITS: PublishedReferenceLimit[] = [
  {
    id: 'netlify-credits',
    provider: 'netlify',
    category: 'Hạn mức sử dụng',
    name: 'Netlify Free usage credits',
    publishedLimit: '300 credits / tháng',
    notes: 'Một pool credits theo team cho các web project trên gói credit-based; tài khoản legacy có thể theo cách tính khác. Đây là hạn mức công bố, không phải số credits còn lại của tài khoản; ứng dụng chưa đo usage Netlify.',
    sourceUrl: 'https://docs.netlify.com/manage/accounts-and-billing/billing/billing-for-credit-based-plans/how-credits-work/',
    checkedAt: '2026-09-27',
  },
  {
    id: 'netlify-credit-rates',
    provider: 'netlify',
    category: 'Cách tính credit',
    name: 'Netlify Free credit rates',
    publishedLimit: 'Deploy production 15; compute 10/GB-giờ; bandwidth 20/GB; request 2/10.000',
    notes: 'Áp dụng cho gói credit-based. Đây là đơn giá tiêu thụ trong pool credits, không phải bốn quota riêng và không được dùng để suy ra usage từ số deploy của ứng dụng.',
    sourceUrl: 'https://docs.netlify.com/manage/accounts-and-billing/billing/billing-for-credit-based-plans/how-credits-work/',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-database',
    provider: 'supabase',
    category: 'Cơ sở dữ liệu',
    name: 'Supabase Database Size',
    publishedLimit: '500 MB PostgreSQL',
    notes: 'Quota database theo project. API hiện tại chỉ đo filesystem size/used; không thể dùng thay cho mức Database Size theo quota Free.',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-storage',
    provider: 'supabase',
    category: 'Lưu trữ tệp',
    name: 'Supabase Storage Quota',
    publishedLimit: '1 GB Dung lượng tệp',
    notes: 'Hạn mức tổng dung lượng tệp trong các bucket. Ứng dụng chưa đo tổng Storage usage từ Management API.',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-egress-uncached',
    provider: 'supabase',
    category: 'Băng thông',
    name: 'Supabase uncached egress',
    publishedLimit: '5 GB / chu kỳ thanh toán',
    notes: 'Quota uncached riêng 5 GB của gói Free ở cấp organization; usage có thể lọc theo project trong trang usage. Không cộng với cached egress thành một pool.',
    sourceUrl: 'https://supabase.com/docs/guides/platform/manage-your-usage/egress',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-egress-cached',
    provider: 'supabase',
    category: 'Băng thông',
    name: 'Supabase cached egress',
    publishedLimit: '5 GB / chu kỳ thanh toán',
    notes: 'Quota cached riêng 5 GB của gói Free ở cấp organization; usage có thể lọc theo project trong trang usage. Ứng dụng chưa đo usage billing này qua API.',
    sourceUrl: 'https://supabase.com/docs/guides/platform/manage-your-usage/egress',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-mau',
    provider: 'supabase',
    category: 'Người dùng hoạt động',
    name: 'Supabase MAU',
    publishedLimit: '50.000 MAU / tháng',
    notes: 'Hạn mức MAU của gói Free; số user trong database ứng dụng không được dùng thay cho MAU của Supabase. Đối chiếu tại dashboard.',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-realtime-messages',
    provider: 'supabase',
    category: 'Kết nối thời gian thực',
    name: 'Supabase Realtime messages',
    publishedLimit: '2 triệu tin nhắn / tháng',
    notes: 'Hạn mức tin nhắn Realtime của gói Free. API request Realtime của ứng dụng không phải số message tính phí; đối chiếu tại dashboard.',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-realtime-connections',
    provider: 'supabase',
    category: 'Kết nối thời gian thực',
    name: 'Supabase Realtime concurrent connections',
    publishedLimit: '200 kết nối đồng thời',
    notes: 'Peak connection limit của gói Free. Ứng dụng chưa đo peak connections qua Management API.',
    sourceUrl: 'https://supabase.com/docs/guides/realtime/limits',
    checkedAt: '2026-09-27',
  },
  {
    id: 'brevo-daily-emails',
    provider: 'brevo',
    category: 'Email giao dịch',
    name: 'Brevo Free Email Limit',
    publishedLimit: '300 email / ngày',
    notes: 'Quota tài khoản do Brevo công bố. Bộ đếm trong ứng dụng là lượt giữ suất theo ngày Việt Nam, không đại diện toàn bộ mức dùng tài khoản Brevo.',
    sourceUrl: 'https://help.brevo.com/hc/en-us/articles/208580669-FAQs-What-are-the-limits-of-the-Free-plan',
    checkedAt: '2026-09-27',
  },
  {
    id: 'brevo-contacts',
    provider: 'brevo',
    category: 'Danh bạ',
    name: 'Brevo Free contacts',
    publishedLimit: '100.000 contacts',
    notes: 'Hạn mức contacts của tài khoản Free, không phải số invitation trong ứng dụng. Ứng dụng chưa đọc usage contacts qua adapter.',
    sourceUrl: 'https://help.brevo.com/hc/en-us/articles/208580669-FAQs-What-are-the-limits-of-the-Free-plan',
    checkedAt: '2026-09-27',
  },
  {
    id: 'brevo-free-branding',
    provider: 'brevo',
    category: 'Điều kiện gói',
    name: 'Brevo Free branding',
    publishedLimit: 'Email có nhãn “Sent with Brevo”',
    notes: 'Đây là điều kiện của gói Free, không phải một số đo usage. Xác thực domain không tự gỡ nhãn này.',
    sourceUrl: 'https://help.brevo.com/hc/en-us/articles/208580669-FAQs-What-are-the-limits-of-the-Free-plan',
    checkedAt: '2026-09-27',
  },
  {
    id: 'github-actions',
    provider: 'github',
    category: 'Actions (repo private)',
    name: 'GitHub Free hosted runners',
    publishedLimit: '2.000 phút / tháng; 500 MB artifacts + Packages dùng chung',
    notes: 'Allowance ở cấp tài khoản/chủ repo; artifacts và Packages chia sẻ 500 MB. Cache riêng 10 GB/repository; Git LFS riêng. Ứng dụng không đọc usage GitHub. Phút chỉ trừ khi standard GitHub-hosted runner chạy cho repo private; public repo và self-hosted có điều kiện khác.',
    sourceUrl: 'https://docs.github.com/en/billing/concepts/product-billing/github-actions',
    checkedAt: '2026-09-27',
  },
  {
    id: 'github-actions-cache',
    provider: 'github',
    category: 'Actions cache',
    name: 'GitHub Actions cache',
    publishedLimit: '10 GB / repository',
    notes: 'Cache là quota riêng với artifacts/Packages và Git LFS. Ứng dụng không đọc usage GitHub; chỉ đối chiếu tại billing/settings.',
    sourceUrl: 'https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows',
    checkedAt: '2026-09-27',
  },
];

export const DIRECT_DASHBOARD_LINKS: DirectDashboardLink[] = [
  {
    provider: 'Netlify',
    name: 'Netlify Usage & Billing',
    url: 'https://app.netlify.com/teams',
    description: 'Kiểm tra chi tiết credit tiêu thụ, deploy và băng thông hàng tháng.',
  },
  {
    provider: 'Supabase',
    name: 'Supabase Project Dashboard',
    url: 'https://supabase.com/dashboard',
    description: 'Xem báo cáo Database, Storage, Egress, MAU và Realtime trực tiếp.',
  },
  {
    provider: 'Brevo',
    name: 'Brevo Account & SMTP Usage',
    url: 'https://app.brevo.com/settings/usage',
    description: 'Xem hạn mức email giao dịch, thống kê gửi và logs thời gian thực.',
  },
  {
    provider: 'GitHub',
    name: 'GitHub Billing & Licensing',
    url: 'https://github.com/settings/billing',
    description: 'Quản lý gói tài khoản GitHub, dung lượng repo và quota Actions.',
  },
];
