import type { PublishedReferenceLimit, DirectDashboardLink } from '../contracts';

export const PUBLISHED_REFERENCE_LIMITS: PublishedReferenceLimit[] = [
  {
    id: 'netlify-credits',
    provider: 'netlify',
    category: 'Hạn mức sử dụng',
    name: 'Netlify Free usage credits',
    publishedLimit: '300 credits / tháng',
    notes: 'Credits dùng chung cho production deploy, compute, form submissions, bandwidth và web requests. Ứng dụng chưa đo mức tiêu thụ tài khoản.',
    sourceUrl: 'https://www.netlify.com/pricing/',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-database',
    provider: 'supabase',
    category: 'Cơ sở dữ liệu',
    name: 'Supabase Database Size',
    publishedLimit: '500 MB PostgreSQL',
    notes: 'Quota database theo project. API hiện tại chỉ đo filesystem size/used; không thể dùng thay cho mức Database Size theo quota Free.',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-storage',
    provider: 'supabase',
    category: 'Lưu trữ tệp',
    name: 'Supabase Storage Quota',
    publishedLimit: '1 GB Dung lượng tệp',
    notes: 'Hạn mức tổng dung lượng tệp trong các bucket. Ứng dụng chưa đo tổng Storage usage từ Management API.',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-egress',
    provider: 'supabase',
    category: 'Băng thông',
    name: 'Supabase Network Egress',
    publishedLimit: '5 GB uncached + 5 GB cached / chu kỳ thanh toán',
    notes: 'Không gộp chung hai loại egress; tính trên toàn bộ API, Auth và Storage.',
    sourceUrl: 'https://supabase.com/docs/guides/platform/manage-your-usage/egress',
    checkedAt: '2026-09-27',
  },
  {
    id: 'supabase-realtime',
    provider: 'supabase',
    category: 'Kết nối thời gian thực',
    name: 'Supabase Realtime Connections & Messages',
    publishedLimit: '200 kết nối đồng thời, 2 triệu tin nhắn / tháng',
    notes: 'Hạn mức công bố của gói Free; usage Realtime hiện không được đo trong ứng dụng.',
    sourceUrl: 'https://supabase.com/docs/guides/realtime/limits',
    checkedAt: '2026-09-27',
  },
  {
    id: 'brevo-daily-emails',
    provider: 'brevo',
    category: 'Email giao dịch',
    name: 'Brevo Free Email Limit',
    publishedLimit: '300 email / ngày',
    notes: 'Quota tài khoản do Brevo công bố. Bộ đếm trong ứng dụng là lượt giữ suất theo ngày Việt Nam, không đại diện toàn bộ mức dùng tài khoản Brevo.',
    sourceUrl: 'https://help.brevo.com/hc/en-us/articles/208580669-FAQs-What-are-the-limits-of-the-Free-plan',
    checkedAt: '2026-09-27',
  },
  {
    id: 'github-actions',
    provider: 'github',
    category: 'Actions (repo private)',
    name: 'GitHub Free hosted runners',
    publishedLimit: '2.000 phút / tháng; 500 MB artifacts + Packages dùng chung',
    notes: 'Cache có quota riêng 10 GB/repository; Git LFS cũng là quota riêng. Ứng dụng không đọc mức dùng GitHub; phút chỉ được tính khi workflow chạy trên hosted runner của repo private.',
    sourceUrl: 'https://docs.github.com/en/billing/concepts/product-billing/github-actions',
    checkedAt: '2026-09-27',
  },
];

export const DIRECT_DASHBOARD_LINKS: DirectDashboardLink[] = [
  {
    provider: 'Netlify',
    name: 'Netlify Usage & Billing',
    url: 'https://app.netlify.com/teams',
    description: 'Kiểm tra chi tiết credit tiêu thụ, deploy và băng thông hàng tháng.',
  },
  {
    provider: 'Supabase',
    name: 'Supabase Project Dashboard',
    url: 'https://supabase.com/dashboard',
    description: 'Xem báo cáo Database, Storage, Egress, MAU và Realtime trực tiếp.',
  },
  {
    provider: 'Brevo',
    name: 'Brevo Account & SMTP Usage',
    url: 'https://app.brevo.com/settings/usage',
    description: 'Xem hạn mức email giao dịch, thống kê gửi và logs thời gian thực.',
  },
  {
    provider: 'GitHub',
    name: 'GitHub Billing & Licensing',
    url: 'https://github.com/settings/billing',
    description: 'Quản lý gói tài khoản GitHub, dung lượng repo và quota Actions.',
  },
];
