import type { PublishedReferenceLimit, DirectDashboardLink } from '../contracts';

export const PUBLISHED_REFERENCE_LIMITS: PublishedReferenceLimit[] = [
  {
    id: 'netlify-credits',
    provider: 'netlify',
    category: 'Xây dựng & Băng thông',
    name: 'Netlify Build Credits & Bandwidth',
    publishedLimit: '300 credits / tháng, 100 GB Egress',
    notes: 'Credit trừ theo thời gian build (x1 tiêu chuẩn). Chưa có public API đọc quota tự động.',
    sourceUrl: 'https://docs.netlify.com/manage/accounts-and-billing/billing/billing-for-credit-based-plans/how-credits-work/',
    checkedAt: '2026-09-24',
  },
  {
    id: 'supabase-database',
    provider: 'supabase',
    category: 'Cơ sở dữ liệu',
    name: 'Supabase Database Size',
    publishedLimit: '500 MB PostgreSQL',
    notes: 'Kích thước cơ sở dữ liệu logical. Khác với filesystem disk size trong API hạ tầng.',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-24',
  },
  {
    id: 'supabase-storage',
    provider: 'supabase',
    category: 'Lưu trữ tệp',
    name: 'Supabase Storage Quota',
    publishedLimit: '1 GB Dung lượng tệp',
    notes: 'Dành cho bucket audio (private) và banners (public).',
    sourceUrl: 'https://supabase.com/pricing',
    checkedAt: '2026-09-24',
  },
  {
    id: 'supabase-egress',
    provider: 'supabase',
    category: 'Băng thông',
    name: 'Supabase Network Egress',
    publishedLimit: '5 GB / tháng (Cached & Uncached riêng biệt)',
    notes: 'Không gộp chung hai loại egress; tính trên toàn bộ API, Auth và Storage.',
    sourceUrl: 'https://supabase.com/docs/guides/platform/manage-your-usage',
    checkedAt: '2026-09-24',
  },
  {
    id: 'supabase-realtime',
    provider: 'supabase',
    category: 'Kết nối thời gian thực',
    name: 'Supabase Realtime Connections & Messages',
    publishedLimit: '200 kết nối đồng thời, 2 triệu tin nhắn / tháng',
    notes: 'Chỉ publish bảng invitations cho Host lắng nghe RSVP; khách mời không subscribe.',
    sourceUrl: 'https://supabase.com/docs/guides/realtime/limits',
    checkedAt: '2026-09-24',
  },
  {
    id: 'brevo-daily-emails',
    provider: 'brevo',
    category: 'Email giao dịch',
    name: 'Brevo Free Email Limit',
    publishedLimit: '300 email / ngày',
    notes: 'Reset hàng ngày theo giờ UTC của Brevo. Mọi thư gửi đều kèm nhãn "Sent with Brevo".',
    sourceUrl: 'https://help.brevo.com/hc/en-us/articles/208580669-FAQs-What-are-the-limits-of-the-Free-plan',
    checkedAt: '2026-09-24',
  },
  {
    id: 'github-actions',
    provider: 'github',
    category: 'Mã nguồn & CI/CD',
    name: 'GitHub Free Private Repository',
    publishedLimit: '2.000 phút Actions / tháng, 500 MB Packages',
    notes: 'V1 deploy tự động qua Netlify Git integration, không tiêu hao phút Actions nếu không chạy CI riêng.',
    sourceUrl: 'https://docs.github.com/en/billing/get-started/introduction-to-billing',
    checkedAt: '2026-09-24',
  },
];

export const DIRECT_DASHBOARD_LINKS: DirectDashboardLink[] = [
  {
    provider: 'Netlify',
    name: 'Netlify Usage & Billing',
    url: 'https://app.netlify.com/teams',
    description: 'Kiểm tra chi tiết credit tiêu thụ, deploy và băng thông hàng tháng.',
  },
  {
    provider: 'Supabase',
    name: 'Supabase Project Dashboard',
    url: 'https://supabase.com/dashboard',
    description: 'Xem báo cáo Database, Storage, Egress, MAU và Realtime trực tiếp.',
  },
  {
    provider: 'Brevo',
    name: 'Brevo Account & SMTP Usage',
    url: 'https://app.brevo.com/settings/usage',
    description: 'Xem hạn mức email giao dịch, thống kê gửi và logs thời gian thực.',
  },
  {
    provider: 'GitHub',
    name: 'GitHub Billing & Licensing',
    url: 'https://github.com/settings/billing',
    description: 'Quản lý gói tài khoản GitHub, dung lượng repo và quota Actions.',
  },
];
