// Generated by scripts/optimize-template-assets.mjs. Edit artwork under images/.
import image0 from './assets/bg-pattern-top.webp';
import image1 from './assets/bg-wave-blue.webp';
import image2 from './assets/cap-icon.webp';
import image3 from './assets/corner-leaf.webp';
import image4 from './assets/flower-decor.webp';
import image5 from './assets/gallery-1.webp';
import image6 from './assets/gallery-2.webp';
import image7 from './assets/gallery-3.webp';
import image8 from './assets/gallery-4.webp';
import image9 from './assets/gallery-5.webp';
import image10 from './assets/gallery-6.webp';
import image11 from './assets/hero-portrait.webp';
import image12 from './assets/marquee-1.webp';
import image13 from './assets/marquee-2.webp';
import image14 from './assets/marquee-3.webp';
import image15 from './assets/marquee-4.webp';
import image16 from './assets/sparkle.webp';
import image17 from './assets/spin-badge.webp';
import image18 from './assets/story-portrait.webp';
import image19 from './assets/thank-you-banner.webp';

export const templateAssets: Record<string, string> = {
  "bg-pattern-top.png": image0.src,
  "bg-wave-blue.png": image1.src,
  "cap-icon.png": image2.src,
  "corner-leaf.png": image3.src,
  "flower-decor.png": image4.src,
  "gallery-1.webp": image5.src,
  "gallery-2.webp": image6.src,
  "gallery-3.webp": image7.src,
  "gallery-4.webp": image8.src,
  "gallery-5.webp": image9.src,
  "gallery-6.webp": image10.src,
  "hero-portrait.webp": image11.src,
  "marquee-1.webp": image12.src,
  "marquee-2.webp": image13.src,
  "marquee-3.webp": image14.src,
  "marquee-4.webp": image15.src,
  "sparkle.png": image16.src,
  "spin-badge.png": image17.src,
  "story-portrait.webp": image18.src,
  "thank-you-banner.webp": image19.src,
  "bg-wave-cream.png": image0.src,
  "bg-wave-dark.png": image1.src,
};
